ARG NODE_IMAGE=node:18-alpine3.15

FROM $NODE_IMAGE AS base
RUN apk --no-cache add dumb-init
RUN mkdir -p /home/node/app && chown node:node /home/node/app
WORKDIR /home/node/app
# start pagkage for pupeteer
ENV CHROME_BIN="/usr/bin/chromium-browser"\
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD="true"

RUN set -x \
  && apk update \
  && apk upgrade \
  && apk add --no-cache \
  udev \
  ttf-freefont \
  chromium
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools
# yarn
RUN npm install yarn
RUN npm install -g @nestjs/cli
# end pagkage for pupeteer
USER node
RUN mkdir tmp

COPY --chown=node:node ./package*.json ./
RUN yarn
COPY --chown=node:node . .

